version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      # MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3306"
    volumes:
      - ./tododb-volume:/var/lib/mysql

volumes:
  tododb-volume:
    external: true
